from __future__ import annotations

from .common import (
    bounded_int as _bounded_int,
    bounded_float as _bounded_float,
)

import re
import time
from dataclasses import replace
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from ..models import CompanySource, DiscoveredJob, JobSourceType
from ..normalization import canonicalize_url
from .base import CompanyRateLimiter, HttpClient
from .public_portal import PortalProfile, PortalTarget, PublicPortalJobSource


_AMAZON_HOSTS = {"amazon.jobs", "www.amazon.jobs"}
_LOCALE_RE = re.compile(r"^[a-z]{2}(?:-[a-z]{2})?$", re.IGNORECASE)
_PAGING_QUERY_NAMES = {"offset", "result_limit", "sort", "cache"}

_PROFILE = PortalProfile(
    source_type=JobSourceType.AMAZON_JOBS,
    platform_name="Amazon Jobs",
    job_url_patterns=(
        re.compile(
            r"/(?:[a-z]{2}(?:-[a-z]{2})?/)?jobs/\d+(?:/[^/?#]+)?/?(?:\?.*)?$",
            re.IGNORECASE,
        ),
    ),
    listing_url_patterns=(
        re.compile(r"/(?:[a-z]{2}(?:-[a-z]{2})?/)?search/?", re.IGNORECASE),
    ),
    allowed_host_suffixes=("amazon.jobs",),
)


def parse_amazon_jobs_careers_url(value: str) -> PortalTarget:
    """Normalize an Amazon Jobs URL to the public search page.

    Amazon owns this source, so the connector deliberately accepts only the
    official ``amazon.jobs`` hostname. Root, search, and individual job URLs
    normalize to one locale-aware search catalog. Company/location filters in
    the query string are retained, while paging controls are generated by the
    connector for bounded scanning.
    """

    canonical = canonicalize_url(value)
    parsed = urlsplit(canonical)
    host = (parsed.hostname or "").casefold().rstrip(".")
    if host not in _AMAZON_HOSTS:
        raise ValueError("Amazon Jobs careers_url must use the official amazon.jobs host")
    if parsed.username is not None or parsed.password is not None:
        raise ValueError("Amazon Jobs careers_url cannot contain credentials")

    segments = [segment for segment in parsed.path.split("/") if segment]
    locale = "en"
    for segment in segments[:2]:
        if _LOCALE_RE.fullmatch(segment):
            locale = segment
            break

    preserved_query = [
        (name, item)
        for name, item in parse_qsl(parsed.query, keep_blank_values=True)
        if name.casefold() not in _PAGING_QUERY_NAMES
    ]
    listing = canonicalize_url(
        urlunsplit(
            (
                "https",
                "www.amazon.jobs",
                f"/{locale}/search",
                urlencode(preserved_query, doseq=True),
                "",
            )
        )
    )
    return PortalTarget(listing, ("www.amazon.jobs",))


class AmazonJobsJobSource:
    """Collect public corporate postings from Amazon's own career site.

    The connector uses the public, server-rendered search and job-detail pages.
    It does not access candidate accounts, internal employee jobs, or the
    separate hourly-hiring application system.
    """

    def __init__(
        self,
        http_client: HttpClient | None = None,
        *,
        rate_limiter: CompanyRateLimiter | None = None,
        clock=time.monotonic,
    ) -> None:
        self.portal = PublicPortalJobSource(
            _PROFILE,
            http_client=http_client,
            rate_limiter=rate_limiter,
            clock=clock,
        )
        self.clock = clock

    def fetch_jobs(self, source: CompanySource) -> list[DiscoveredJob]:
        target = parse_amazon_jobs_careers_url(source.careers_url)
        max_pages = _bounded_int(source.filters.get("max_pages"), 10, 1, 50)
        max_jobs = _bounded_int(source.filters.get("max_jobs"), 1000, 1, 5000)
        page_size = _bounded_int(
            source.filters.get("amazon_page_size"), 10, 1, 100
        )
        detail_limit = _bounded_int(
            source.filters.get("detail_fetch_limit"), max_jobs, 0, max_jobs
        )
        budget = _bounded_float(
            source.filters.get("fetch_budget_seconds"), 0.0, 0.0, 300.0
        )
        deadline = self.clock() + budget if budget > 0 else None

        listing = urlsplit(target.listing_url)
        base_query = [
            (name, item)
            for name, item in parse_qsl(listing.query, keep_blank_values=True)
            if name.casefold() not in _PAGING_QUERY_NAMES
        ]
        jobs_by_external_id: dict[str, DiscoveredJob] = {}
        details_remaining = detail_limit

        for page_index in range(max_pages):
            if len(jobs_by_external_id) >= max_jobs:
                break
            if deadline is not None and self.clock() >= deadline:
                break

            remaining_jobs = max_jobs - len(jobs_by_external_id)
            current_page_size = min(page_size, remaining_jobs)
            query = list(base_query)
            query.extend(
                (
                    ("offset", str(page_index * page_size)),
                    ("result_limit", str(current_page_size)),
                    ("sort", "recent"),
                )
            )
            page_url = canonicalize_url(
                urlunsplit(
                    (
                        listing.scheme,
                        listing.netloc,
                        listing.path,
                        urlencode(query, doseq=True),
                        "",
                    )
                )
            )

            page_filters = dict(source.filters)
            page_filters.update(
                {
                    "max_pages": 1,
                    "max_jobs": current_page_size,
                    "detail_fetch_limit": min(details_remaining, current_page_size),
                }
            )
            if deadline is not None:
                page_filters["fetch_budget_seconds"] = max(
                    0.0, deadline - self.clock()
                )
            page_source = replace(
                source,
                careers_url=page_url,
                filters=page_filters,
            )
            page_jobs = self.portal.fetch_jobs(
                page_source,
                PortalTarget(page_url, target.allowed_domains),
            )
            if not page_jobs:
                break

            new_count = 0
            for job in page_jobs:
                if job.external_job_id not in jobs_by_external_id:
                    new_count += 1
                jobs_by_external_id[job.external_job_id] = job
                if len(jobs_by_external_id) >= max_jobs:
                    break
            detail_attempts = sum(
                1
                for job in page_jobs
                if str((job.metadata or {}).get("detail_status") or "").casefold()
                in {"fetched", "failed"}
            )
            details_remaining = max(0, details_remaining - detail_attempts)
            if new_count == 0 or len(page_jobs) < current_page_size:
                break

        return list(jobs_by_external_id.values())

    def fetch_job_description(self, job: DiscoveredJob) -> str:
        return self.portal.fetch_job_description(
            job,
            parse_amazon_jobs_careers_url(job.canonical_url),
        )
