"""Shared Career Bridge domain foundation.

The shared package intentionally has no Flask, AWS, OpenAI, audio-processing,
or document-generation dependency. The imported products remain isolated under
``products/`` and connect through the ports in :mod:`career_bridge.ports`.

``JobApplication`` is the aggregate root. It links one candidate and one target
job to the resume-tailoring and interview-practice lifecycle.
"""

from career_bridge.presentation import (
    APPLICATION_BUILDER_STEPS,
    CAREER_NAVIGATION,
    ApplicationBuilderStep,
    ApplicationDashboardItem,
    CareerNavigationSection,
    application_builder_steps,
    validate_application_builder_model_alignment,
    career_navigation,
    validate_navigation_model_alignment,
)

from career_bridge.domain import (
    ActionPriority,
    ActionStatus,
    ApplicationStatus,
    ApplicationStatusChange,
    AuthSession,
    CandidateProfile,
    CareerBackground,
    CareerDocument,
    CareerExperience,
    DocumentKind,
    EducationRecord,
    EvidenceItem,
    EvidenceLibrary,
    EvidenceType,
    EvidenceVerificationStatus,
    ImprovementAction,
    ImprovementArea,
    InterviewKind,
    InterviewPreparation,
    InterviewQuestion,
    JobApplication,
    JobApplicationBundle,
    MockInterviewSession,
    PreparationStatus,
    ProcessingStatus,
    Resume,
    Score,
    ScoreKind,
    Scorecard,
    SupportCase,
    SupportStatus,
    TailoredResumeVersion,
    TargetJobDescription,
    Transcript,
    TranscriptSegment,
    UserProfile,
)

__all__ = [
    "APPLICATION_BUILDER_STEPS",
    "ApplicationBuilderStep",
    "ApplicationDashboardItem",
    "application_builder_steps",
    "validate_application_builder_model_alignment",
    "validate_navigation_model_alignment",
    "career_navigation",
    "CareerNavigationSection",
    "CAREER_NAVIGATION",
    "ActionPriority",
    "ActionStatus",
    "ApplicationStatus",
    "ApplicationStatusChange",
    "AuthSession",
    "CandidateProfile",
    "CareerBackground",
    "CareerDocument",
    "CareerExperience",
    "DocumentKind",
    "EducationRecord",
    "EvidenceItem",
    "EvidenceLibrary",
    "EvidenceType",
    "EvidenceVerificationStatus",
    "ImprovementAction",
    "ImprovementArea",
    "InterviewKind",
    "InterviewPreparation",
    "InterviewQuestion",
    "JobApplication",
    "JobApplicationBundle",
    "MockInterviewSession",
    "PreparationStatus",
    "ProcessingStatus",
    "Resume",
    "Score",
    "ScoreKind",
    "Scorecard",
    "SupportCase",
    "SupportStatus",
    "TailoredResumeVersion",
    "TargetJobDescription",
    "Transcript",
    "TranscriptSegment",
    "UserProfile",
]
